name: Build MacOS
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install setuptools wheel
      - run: python3 -m pip install -r requirements.txt
      - run: pyinstaller ./src/cfmdown.py --onefile --name cfmdown --python-option u
      - run: pyinstaller ./src/cfmparse.py --onefile --name cfmparse --python-option u
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/*
          retention-days: 1